version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: host

  db:
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  lms:
    image: erseco/alpine-moodle
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - SITE_URL=http://localhost:8080
      - DB_TYPE=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PREFIX=mdl_
      - SSLPROXY=false
      - MOODLE_EMAIL=user@example.com
      - MOODLE_LANGUAGE=en
      - MOODLE_SITENAME=git-moodle-bridge
      - MOODLE_USERNAME=openscript
      - MOODLE_PASSWORD=openscript
      - SMTP_HOST=smtp
      - SMTP_PORT=1025
      - SMTP_USER=user@example.com
      - MOODLE_MAIL_NOREPLY_ADDRESS=noreply@localhost
      - MOODLE_MAIL_PREFIX=[moodle]
    ports:
      - 8080:8080
    volumes:
      - lms-data:/var/www/moodledata
      - lms-html:/var/www/html
    depends_on:
      - db

  smtp:
    image: dockage/mailcatcher
    ports:
      - 8081:1080


volumes:
  db-data: null
  lms-data: null
  lms-html: null
